---
# Note: This playbook is only to illustrate all module functionality. Running both add from change list and add from file
#       will fail since only one PCA can run on NAE at a time.
- name: NAE TESTING
  hosts: all
  vars:
    nae_login: &nae_login
      host: 173.36.219.127
      port: 443
      username: admin
      password: ins3965!ins3965!
    validate_certs: False
  tasks:
    - name: Create a pre-change analysis from file
      nae_tcam:
        <<: *nae_login
        file: tcam_out
        ag_name: Migration
