---
- name: Add a tenant
  hosts: '{{ host }}'
  gather_facts: no
  connection: local

  #  vars_files:
  #    - apic-vars.yaml 


  tasks:

    - name: Creating VRF
      aci_vrf:
        tenant: "{{tenant}}"
        vrf_name: "{{vrf_name}}"
        host: "{{host}}"
        username: "{{username}}"
        private_key:  "{{ private_key }}"
        certificate_name: "{{ certificate_name }}"
        validate_certs: no
        state: present
        use_proxy: no
      delegate_to: localhost      


    
# usage: ansible-playbook  add_tenant.yaml -i hosts -vvv
