---
- name: Add a tenant
  hosts: '{{ host }}'
  gather_facts: no
  connection: local

  #  vars_files:
  #    - apic-vars.yaml 


  tasks:

    - name: Create a subnet
      aci_bd_subnet:
        host: "{{host}}"
        username: "{{username}}"
        private_key:  "{{ private_key }}"
        certificate_name: "{{ certificate_name }}"
        validate_certs: no
        tenant: "{{tenant}}"
        bd: "{{bdname}}"
        gateway: "{{bdIp}}"
        mask: "{{bdMask}}"
        state: present
        use_proxy: no
      delegate_to: localhost



# usage: ansible-playbook  add_subnet.yaml -i hosts -vvv
