---
- name: Add a tenant
  hosts: '{{ host }}'
  gather_facts: no
  connection: local

  #  vars_files:
  #    - apic-vars.yaml 


  tasks:


    - name: Create EPG
      aci_epg:
        tenant: "{{tenant}}"
        app_profile_name: "{{app_profile_name}}"
        epg_name:  "{{epg_name}}"
        bd_name: "{{bdname}}"
        host: "{{host}}"
        username: "{{username}}"
        private_key:  "{{ private_key }}"
        certificate_name: "{{ certificate_name }}"
        validate_certs: no
        state: present
        use_proxy: no
      delegate_to: localhost


# usage: ansible-playbook  7.createEPG.yaml -i hosts -vvv
