---
- name: Add a tenant
  hosts: '{{ host }}'
  gather_facts: no
  connection: local

  #  vars_files:
  #    - apic-vars.yaml 


  tasks:

    - name: Create web_epg contract
      aci_epg_to_contract:
        tenant: "{{tenant}}"
        app_profile_name: "{{app_profile_name}}"
        epg_name:  "{{epg_name}}"
        contract:  "{{contract_name}}"
        contract_type: "{{ contract_type }}"
        host: "{{host}}"
        username: "{{username}}"
        private_key:  "{{ private_key }}"
        certificate_name: "{{ certificate_name }}"
        validate_certs: no 
        use_proxy: no
      delegate_to: localhost        

# usage: ansible-playbook  8.addEPG2contract.yaml -i hosts -vvv
