---
- name: Add a tenant
  hosts: '{{ host }}'
  gather_facts: no
  connection: local

  #  vars_files:
  #    - apic-vars.yaml 


  tasks:
    - name:  VMM Binding to EPGs
      aci_epg_to_domain:
        app_profile_name:  "{{app_profile_name}}"
        tenant: "{{tenant}}"
        epg_name: "{{epg_name}}"
        domain_type:  vmm
        vm_provider:  vmware
        domain_profile: "{{vmm_domain}}"
        deploy_immediacy: immediate
        host: "{{host}}"
        username: "{{username}}"
        private_key:  "{{ private_key }}"
        certificate_name: "{{ certificate_name }}"
        validate_certs: no
        use_proxy: no
      delegate_to: localhost

# usage: ansible-playbook  9.vmmBinding2epg.yaml -i hosts -vvv
