---

- name: Verify ACI Config
  hosts: all
  connection: local
  collections:
    - cisco.nae
  gather_facts: no
  vars:
    nae_login: &nae_login
        host: "put IP of NAE here"
        username: admin
        password: "put password of NAE here"
    PreChangeAnalysisName: Jenkins3_27-1    # this will be the name of the Pre Change Verification in NAE
    validate_certs: False
  
  tasks:
    - name: Create a pre-change analysis
      cisco.nae.nae_prechange:
        <<: *nae_login
        ag_name: "DMZ-RCDN-Site1" #  make sure to have the correct site name as shown in NAE
        name: "{{ PreChangeAnalysisName }}"
        state: present
        verify: true
        file: config.json

    - name: Get PCV Result
      cisco.nae.nae_prechange:
        <<: *nae_login
        ag_name: "DMZ-RCDN-Site1"  #  make sure to have the correct site name as shown in NAE
        name: "{{ PreChangeAnalysisName }}"
        state: query
        verify: True
        ignore_sm:
          # We ignore this info event or the pipeline will always fail. 
          - APP_EPG_NOT_DEPLOYED
